[Distribution]
Distribution=arch

[Output]
Format=disk

[Content]
Bootable=yes
Timezone=UTC
Packages=
    base
    bind
    bird
    cloud-init
    cni-plugins
    conntrack-tools
    containerd
    crictl
    ethtool
    htop
    iotop
    less
    linux-lts
    openbsd-netcat
    openssh
    prometheus-node-exporter
    socat
    strongswan
    sudo
    tcpdump
    traceroute
    vim
    which
VolatilePackages=
    ndppd
BuildPackages=
    base-devel
    git
WithDocs=no
KernelCommandLine=
    audit=0
    systemd.ssh_auto=no
    zswap.enabled=0

[Build]
Environment=
    KUBERNETES_VERSION
    KUBERNETES_RELEASE
WithNetwork=true
