[Distribution]
Distribution=arch

[Output]
Format=disk

[Content]
Bootable=yes
Timezone=UTC
RootPassword=hashed:
Packages=
    base
    cloud-init
    cni-plugins
    conntrack-tools
    containerd
    dnsmasq
    ethtool
    htop
    iotop
    linux-lts
    nftables
    openbsd-netcat
    openssh
    prometheus-node-exporter
    socat
    strongswan
    sudo
    tcpdump
    traceroute
    vim

[Build]
Environment=
    KUBERNETES_VERSION
    KUBERNETES_RELEASE
WithNetwork=true
