name: Build
on:
  pull_request:
  push:
    branches:
      - master
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
      upload:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Kubernetes ${{ matrix.kubernetes.version }} (${{ matrix.base.name }}) [${{ matrix.base.profile }}]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        kubernetes:
          - version: v1.35.0
            release: v0.20.1
        base:
          - name: Arch Linux
            directory: archlinux
            profile: vm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up mkosi
        uses: systemd/mkosi@v26
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends \
            libarchive-tools \
            mtools \
            python3-pefile \
            systemd-boot \
            systemd-ukify
      - name: Build image
        working-directory: ${{ matrix.base.directory }}
        env:
          IMAGE_ID: ${{ matrix.base.directory }}-${{ matrix.base.profile }}
          IMAGE_VERSION: ${{ inputs.tag || 1 }}
          PROFILE: ${{ matrix.base.profile }}
          KUBERNETES_VERSION: ${{ matrix.kubernetes.version }}
          KUBERNETES_RELEASE: ${{ matrix.kubernetes.release }}
        run: |
          sudo -E \
            mkosi \
              --image-id="$IMAGE_ID" \
              --image-version="$IMAGE_VERSION" \
              --profile="$PROFILE"

          out_dir=/tmp/output
          mkdir -p "$out_dir"
          awk '{ gsub(/^\*/, "", $2); print $2 }' "mkosi.output/${IMAGE_ID}_${IMAGE_VERSION}.SHA256SUMS" | xargs -I {} mv mkosi.output/{} "$out_dir"
          mv "mkosi.output/${IMAGE_ID}_${IMAGE_VERSION}".{manifest,SHA256SUMS} "$out_dir"
      - name: Upload
        if: ${{ inputs.upload || false }}
        uses: svenstaro/upload-release-action@v2
        with:
          tag: ${{ inputs.tag }}
          file: /tmp/output/*
          file_glob: true
