name: Release
on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  publish:
    name: Publish
    uses: ./.github/workflows/publish.yml
    permissions:
      contents: write
    with:
      tag: ${{ github.event.release.tag_name }}
      upload: true
