name: Release
on:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: write
    with:
      tag: ${{ github.event.release.tag_name }}
      upload: true
